output_dir: './outputs'

data:
  data_path: './buffers/data/idae_f1c3/train_32'
  fid_reference_file: './buffers/refs/cf10_32_fid_ref.npz'
  image_size: 32
  num_classes: 1
  num_workers: 8
  latent_norm: False
  latent_multiplier: 1.0

vae:
  type: 'idae_f1c3'
  downsample_ratio: 1

model:
  type: UNet+
  in_chans: 3

train:
  ckpt: "0000000.pt" # <---- resume ckpt, comment to start from scratch
  no_reopt: True
  no_reuni: True
  no_buffer: True
  max_steps: 5000
  global_batch_size: 128
  global_seed: 0
  log_every: 100
  ckpt_every: 1000
  ema_decay: 0.999
optimizer:
  type: 'RAdam'
  lr: 0.0001
  weight_decay: 0.0
  beta1: 0.9
  beta2: 0.999

transport:
  type: EDM
  lab_drop_ratio: 0.1
  consistc_ratio: 1.0
  enhanced_ratio: -0.45
  scaled_cbl_eps: 0.0
  ema_decay_rate: 1.0
  enhanced_range: [0.0, 0.75]
  time_dist_ctrl: [3.5, 3.5, 1.2]
  weight_funcion: Cosine
  wt_cosine_loss: False

sample:
  ckpt: "0005000.pt" # <---- fid should be 6.196598243763958
  type: UNI
  cfg_scale: 0.0
  cfg_interval: [0.25, 1.0]
  sampling_steps: 1
  stochast_ratio: 0.0
  extrapol_ratio: 0.0
  sampling_order: 1
  time_dist_ctrl: [1.1, 0.7, 1.1]
  rfba_gap_steps: [0.001, 0.001]
  per_batch_size: 125
  fid_sample_num: 50000
